import os
import string
import sys

import yaml

sys.path.insert(0, os.path.join(os.path.dirname(os.path.realpath(__file__)), os.pardir, "lib"))
from galaxy.tool_util.unittest_utils.cwl_data import conformance_tests_gen

THIS_DIRECTORY = os.path.dirname(os.path.realpath(__file__))
GALAXY_ROOT_DIR = os.path.abspath(os.path.join(THIS_DIRECTORY, os.pardir))
CWL_API_TESTS_DIRECTORY = os.path.join(GALAXY_ROOT_DIR, "lib", "galaxy_test", "api", "cwl")
INTEGRATION_TESTS_DIRECTORY = os.path.join(GALAXY_ROOT_DIR, "test", "integration")

TEST_FILE_TEMPLATE = string.Template('''"""Test CWL conformance for version ${version}."""

import pytest

from ..test_workflows_cwl import BaseCwlWorkflowsApiTestCase


class TestCwlConformance(BaseCwlWorkflowsApiTestCase):
    """Test case mapping to CWL conformance tests for version ${version}."""
$tests''')

TEST_TEMPLATE = string.Template('''
${marks}    def test_conformance_${version_simple}_${id_}(self):
        """${doc}

        Generated from::

${cwl_test_def}
        """  # noqa: W293
        self.cwl_populator.run_conformance_test("""${version}""", """${doc}"""${timeout_arg})
''')

EXTENDED_TIMEOUT_TESTS: dict[str, dict[str, int]] = {
    "v1.0": {},
    "v1.1": {},
    "v1.2": {
        "flat_crossproduct_flat_crossproduct_scatter": 5,
        "flat_crossproduct_simple_scatter": 5,
        "simple_flat_crossproduct_scatter": 5,
    },
}

SKIP_DOCKER_TEMPLATE = string.Template('''
    @pytest.mark.skip(reason="Requires Docker; tested in test/integration/test_containerized_cwl_conformance.py")
    def test_conformance_${version_simple}_${id_}(self):
        """${doc}"""
        ...
''')

INTEGRATION_FILE_TEMPLATE = string.Template('''"""Integration tests for CWL conformance tests that require Docker.

Generated by scripts/cwl_conformance_to_test_cases.py -- do not edit manually.
"""

import os
import shutil
import unittest

import pytest

from galaxy_test.base.populators import (
    CwlPopulator,
    DatasetPopulator,
    WorkflowPopulator,
)
from galaxy_test.driver.integration_util import IntegrationTestCase

CWL_TOOL_DIRECTORY = os.path.join(
    os.path.dirname(__file__),
    os.pardir,
    "functional",
    "tools",
    "cwl_tools",
)


def _skip_unless_conformance_data():
    """Skip if CWL conformance test data has not been downloaded."""
    if not os.path.isdir(os.path.join(CWL_TOOL_DIRECTORY, "v1.0")):
        raise unittest.SkipTest(
            "CWL conformance test data not found; run: make generate-cwl-conformance-tests"
        )


class TestContainerizedCwlConformance(IntegrationTestCase):
    """CWL conformance tests that require a Docker-enabled job destination."""

    require_admin_user = True
    framework_tool_and_types = True
    container_type = "docker"

    @classmethod
    def handle_galaxy_config_kwds(cls, config):
        super().handle_galaxy_config_kwds(config)
        config["job_config"] = {
            "runners": {
                "local": {
                    "load": "galaxy.jobs.runners.local:LocalJobRunner",
                    "workers": 1,
                }
            },
            "execution": {
                "default": "local_docker",
                "environments": {
                    "local_docker": {
                        "runner": "local",
                        "docker_enabled": True,
                    },
                    "local_upload": {
                        "runner": "local",
                    },
                },
            },
            "tools": [
                {"id": "upload1", "environment": "local_upload"},
            ],
        }
        config["enable_beta_tool_formats"] = True
        config["enable_beta_workflow_modules"] = True
        config["conda_auto_init"] = False
        config["conda_auto_install"] = False
        config["tool_dependency_dir"] = "none"

    @classmethod
    def setUpClass(cls):
        if not shutil.which("docker"):
            raise unittest.SkipTest("docker not found on PATH")
        _skip_unless_conformance_data()
        super().setUpClass()

    def setUp(self):
        super().setUp()
        self.dataset_populator = DatasetPopulator(self.galaxy_interactor)
        self.workflow_populator = WorkflowPopulator(self.galaxy_interactor)
        self.cwl_populator = CwlPopulator(
            self.dataset_populator, self.workflow_populator
        )

    # --- generated test methods below ---
$tests
''')

INTEGRATION_TEST_TEMPLATE = string.Template('''
    @pytest.mark.cwl_docker_required
    def test_conformance_${version_simple}_${id_}(self):
        """${doc}"""
        self.cwl_populator.run_conformance_test("""${version}""", """${doc}""")
''')

EXTENDED_TIMEOUT_TESTS: dict[str, dict[str, int]] = {
    "v1.0": {},
    "v1.1": {},
    "v1.2": {
        "simple_flat_crossproduct_scatter": 5,
    },
}

DOCKER_REQUIRED = {
    "v1.0": [
        "docker_entrypoint",
        "dockeroutputdir",
    ],
    "v1.1": [
        "docker_entrypoint",
        "dockeroutputdir",
        "networkaccess_disabled",
        "stdin_shorcut",
    ],
    "v1.2": [
        "docker_entrypoint",
        "dockeroutputdir",
        "iwd-container-entryname1",
        "networkaccess_disabled",
    ],
}

RED_TESTS = {
    "v1.0": [
        "resreq_step_overrides_wf",
        "valuefrom_wf_step",
    ],
    "v1.1": [
        "cwl_requirements_addition",
        "cwl_requirements_override_expression",
        "cwl_requirements_override_static",
        "inplace_update_on_dir_content",
        "record_output_file_entry_format",
        "resreq_step_overrides_wf",
        "stage_array_dirs",
        "stage_null_array",
        "timelimit_expressiontool",
        "timelimit_invalid_wf",
    ],
    "v1.2": [
        "cond-with-defaults-1",
        "cond-with-defaults-2",
        "cwl_requirements_addition",
        "cwl_requirements_override_expression",
        "cwl_requirements_override_static",
        "filename_with_hash_mark",
        "illegal_symlink",
        "initial_work_dir_for_array_dirs",
        "initial_work_dir_for_null_and_arrays",
        "mixed_version_v12_wf",
        "modify_directory_content",
        "nested_crossproduct_nested_crossproduct_scatter",
        "nested_crossproduct_simple_scatter",
        "record_output_file_entry_format",
        "resreq_step_overrides_wf",
        "simple_nested_crossproduct_scatter",
        "timelimit_expressiontool",
    ],
}


def main():
    if len(sys.argv) != 3:
        raise Exception("Expecting 2 arguments: conformance_tests_dir version")
    conformance_tests_dir = sys.argv[1]
    version = sys.argv[2]
    version_simple = version.replace(".", "_")

    red_tests_list = RED_TESTS[version]
    docker_required_list = DOCKER_REQUIRED.get(version, [])
    extended_timeout_tests = EXTENDED_TIMEOUT_TESTS.get(version, {})
    red_tests_found = set()
    docker_required_found = set()
    all_tests_found = set()

    tests = ""

    for i, conformance_test in enumerate(conformance_tests_gen(os.path.join(conformance_tests_dir, version))):
        test_with_doc = conformance_test.copy()
        if "doc" not in test_with_doc:
            raise Exception(f"No doc in test [{test_with_doc}]")
        del test_with_doc["doc"]
        cwl_test_def = yaml.dump(test_with_doc, default_flow_style=False)
        cwl_test_def = "\n".join(f"            {line}" for line in cwl_test_def.splitlines())
        id_ = conformance_test.get("id", str(i))
        tags = conformance_test.get("tags", [])
        is_red = id_ in red_tests_list
        is_docker_required = id_ in docker_required_list

        timeout_multiplier = extended_timeout_tests.get(id_)
        timeout_arg = f", timeout_multiplier={timeout_multiplier}" if timeout_multiplier else ""
        template_kwargs = {
            "version_simple": version_simple,
            "version": version,
            "doc": conformance_test["doc"],
            "cwl_test_def": cwl_test_def,
            "id_": id_.replace("-", "_"),
            "timeout_arg": timeout_arg,
        }

        if is_docker_required:
            test_body = SKIP_DOCKER_TEMPLATE.safe_substitute(template_kwargs)
            docker_required_found.add(id_)
        else:
            marks = "    @pytest.mark.cwl_conformance\n"
            marks += f"    @pytest.mark.cwl_conformance_{version_simple}\n"
            for tag in tags:
                marks += f"    @pytest.mark.{tag}\n"
            if is_red:
                marks += "    @pytest.mark.red\n"
            else:
                marks += "    @pytest.mark.green\n"
            template_kwargs["marks"] = marks
            test_body = TEST_TEMPLATE.safe_substitute(template_kwargs)

        tests += test_body

        if not {"command_line_tool", "expression_tool", "workflow"}.intersection(tags):
            print(
                f"PROBLEM - test [{id_}] tagged with neither command_line_tool, expression_tool, nor workflow",
                file=sys.stderr,
            )

        if id_ in all_tests_found:
            print(f"PROBLEM - Duplicate id found [{id_}]", file=sys.stderr)
        all_tests_found.add(id_)
        if is_red:
            red_tests_found.add(id_)

    test_file_contents = TEST_FILE_TEMPLATE.safe_substitute(
        {
            "version": version,
            "version_simple": version_simple,
            "tests": tests,
        }
    )

    test_file = os.path.join(CWL_API_TESTS_DIRECTORY, f"test_cwl_conformance_{version_simple}.py")
    with open(test_file, "w") as f:
        f.write(test_file_contents)
    print(f"Finished writing {test_file}")

    for red_test in red_tests_list:
        if red_test not in red_tests_found:
            print(f"PROBLEM - Failed to find annotated red test [{red_test}]", file=sys.stderr)

    for docker_test in docker_required_list:
        if docker_test not in docker_required_found:
            print(f"PROBLEM - Failed to find docker-required test [{docker_test}]", file=sys.stderr)



def generate_docker_integration_tests(conformance_tests_dir):
    """Collect DOCKER_REQUIRED tests across all versions and write integration test file."""
    collected = []
    for version, docker_ids in sorted(DOCKER_REQUIRED.items()):
        version_simple = version.replace(".", "_")
        docker_set = set(docker_ids)
        for conformance_test in conformance_tests_gen(os.path.join(conformance_tests_dir, version)):
            id_ = conformance_test.get("id", "")
            if id_ in docker_set:
                collected.append({
                    "version_simple": version_simple,
                    "version": version,
                    "doc": conformance_test["doc"],
                    "id_": id_.replace("-", "_"),
                })

    if not collected:
        return

    integration_tests = ""
    for kwargs in collected:
        integration_tests += INTEGRATION_TEST_TEMPLATE.safe_substitute(kwargs)

    contents = INTEGRATION_FILE_TEMPLATE.safe_substitute({"tests": integration_tests})
    integration_file = os.path.join(INTEGRATION_TESTS_DIRECTORY, "test_containerized_cwl_conformance.py")
    with open(integration_file, "w") as f:
        f.write(contents)
    print(f"Finished writing {integration_file}")


if __name__ == "__main__":
    main()
