name: Client linting
on:
  push:
    paths:
      - 'client/**'
      - '.github/workflows/js_lint.yaml'
  pull_request:
    paths:
      - 'client/**'
      - '.github/workflows/js_lint.yaml'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  client-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Read Node.js version
        id: node-version
        run: echo "version=$(cat 'client/.node_version')" >> $GITHUB_OUTPUT
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ steps.node-version.outputs.version }}
          cache: 'yarn'
          cache-dependency-path: 'client/yarn.lock'
      - run: yarn install --frozen-lockfile
        working-directory: client
      # Previously these were just yarn calls but we're wrapping them in wrapper
      # scripts so we can capture direct output to publish richer artifacts during
      # Github Actions.
      - name: Run ESLint
        run: bash .ci/eslint_yarn_wrapper.sh
      - name: Run prettier checks
        run: bash .ci/format_check_wrapper.sh
      - name: Run vue-tsc
        run: bash .ci/vue_tsc_wrapper.sh
      - uses: actions/upload-artifact@v5
        if: failure()
        with:
          name: ES Lint report
          path: eslint-report.json
      - uses: actions/upload-artifact@v5
        if: failure()
        with:
          name: TSC report
          path: tsc-report.txt
      - uses: actions/upload-artifact@v5
        if: failure()
        with:
          name: Prettier output
          path: prettier-report.txt
