name: Mulled Unit Tests
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7']
    steps:
      - uses: actions/checkout@v2
        with:
          path: 'galaxy root'
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache pip dir
        uses: actions/cache@v1
        id: pip-cache
        with:
          path: ~/.cache/pip
          key: pip-cache-${{ matrix.python-version }}-${{ hashFiles('galaxy root/requirements.txt') }}
      - name: Install tox
        run: pip install tox
      - name: run tests
        run: tox -e mulled
        working-directory: 'galaxy root'
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Mulled unit test results (${{ matrix.python-version }})
          path: 'galaxy root/run_unit_tests.html'
