name: Toolshed tests
on:
  push:
    paths-ignore:
      - 'doc/**'
      - 'lib/galaxy_test/selenium/**'
  pull_request:
    paths-ignore:
      - 'doc/**'
      - 'lib/galaxy_test/selenium/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']
    steps:
      - uses: actions/checkout@v3
        with:
          path: 'galaxy_root'
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Get full Python version
        id: full-python-version
        shell: bash
        run: echo "version=$(python -c 'import sys; print("-".join(str(v) for v in sys.version_info))')" >> $GITHUB_OUTPUT
      - name: Cache pip dir
        uses: actions/cache@v3
        id: pip-cache
        with:
          path: ~/.cache/pip
          key: pip-cache-${{ matrix.python-version }}-${{ hashFiles('galaxy_root/requirements.txt') }}
      - name: Cache galaxy venv
        uses: actions/cache@v3
        with:
          path: 'galaxy_root/.venv'
          key: gxy-venv-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('galaxy_root/requirements.txt') }}-toolshed
      - name: Run tests
        run: './run_tests.sh -toolshed lib/tool_shed/test/functional/test_shed_repositories.py::TestShedRepositoriesApi::test_reset_on_simple_repository lib/tool_shed/test/functional/test_shed_repositories.py::TestShedRepositoriesApi::test_repo_tars'
        working-directory: 'galaxy_root'
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: Toolshed test results (${{ matrix.python-version }})
          path: 'galaxy_root/run_toolshed_tests.html'
